### ISSUE TITLE
Omit some endpoints in documentation

### ISSUE THREAD

**Issue by sprzenus** [mattpolzin/VaporOpenAPI#5]
I want to document only endpoints under a specified path. For example, I want to document only API, so paths under `/api/v1` but the rest of endpoints shouldn't be in the documentation.

Is it possible with this framework? 

I tried to implement my own method method instead of using `openAPIPathItems(using:)` in the `Vapor.Routes` object to choose paths I want to document but method `openAPIPathOperation(using:)` used in this method is declared as internal so it wan't possible

**Comment by mattpolzin** [comment]
This is possible using OpenAPIKit after having already generated the documentation -- if you truly need to avoid generating the docs instead of just filtering them out after the fact, that would require a change to the VaporOpenAPILibrary.

For example, you probably have the following somewhere in your code:
```swift
let paths = try app.routes.openAPIPathItems(using: jsonEncoder)
```

Instead, filter the paths down and create a new dictionary:
```swift
let filteredPaths = try app.routes
            .openAPIPathItems(using: jsonEncoder)
            .filter { (path, _) in path.components.starts(with: ["api", "v1"]) }
let paths = OrderedDictionary(filteredPaths, uniquingKeysWith: { fst, _ in fst })
```

Let me know if this gets at the core of your question or not!

**Comment by sprzenus** [comment]
Actually, this is what I was looking for. Thanks for help!

**Comment by mattpolzin** [comment]
Great. 

You’re welcome!

**Comment by mattpolzin** [comment]
I just added a method to OpenAPIKit in v 2.4.0 to make this a bit easier.

Now you can:
```swift
let paths = try app.routes
            .openAPIPathItems(using: jsonEncoder)
            .filteringPaths { $0.components.starts(with: ["api", "v1"]) }
```
